# Copyright (c) 2024 Tudor Oancea
name: Create a release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project
        run: uv sync

      - name: Build wheel
        run: uv build

      - name: Upload wheel to PyPI
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - name: Install from PyPI
        run: uv run --with strongpods --no-project -- python -c "from strongpods import *; print(PODS)"
