# Copyright (c) 2024 Tudor Oancea
name: Create a release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.5/install.sh | sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project
        run: uv sync

      - name: Build wheel
        run: uvx --from build pyproject-build --installer uv

      - name: Upload wheel to PyPI
        run: uvx twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

      - name: Install from PyPI
        run: uv run --with strongpods --no-project -- python -c "from strongpods import *; print(PODS)"
